// Конфиг
const SB_URL='https://jttsgizkuyipolcnvanc.supabase.co',SB_KEY='sb_publishable_MV93VmhU8U2I-2m8UquKkw_Eril4zvp',supabase=window.supabase.createClient(SB_URL,SB_KEY);
let state={user:null,balance:0,inventory:[]},cases=[],skins=[],selectedCase=null,selectedCaseId=null,currentCaseSkins=[];

async function init(){console.log('Инициализация...');await checkAuth();await loadData();if(state.user)await loadPlayer();setupModalListeners();updateUI();setupAdminDragDrop();}
function setupAdminDragDrop(){setTimeout(()=>{const e=document.getElementById('case-drop-zone');e&&(e.addEventListener('dragover',allowDrop),e.addEventListener('dragleave',dragLeave),console.log('Drag & drop инициализирован'))},100);}

function setupModalListeners(){document.querySelectorAll('.modal').forEach(e=>{e.addEventListener('click',function(t){t.target===this&&(this.style.display='none')})});}
function showAuth(){showLogin()}function showLogin(){document.getElementById('login-modal').style.display='block'}function showRegister(){document.getElementById('register-modal').style.display='block',document.getElementById('login-modal').style.display='none'}function closeModal(e){document.getElementById(e).style.display='none'}

async function handleRegister(){const e=document.getElementById('register-email').value.trim(),t=document.getElementById('register-password').value.trim(),a=document.getElementById('register-confirm').value.trim(),s=document.getElementById('register-error');if(s.textContent='',!e||!t||!a)return s.textContent='Заполните все поля';if(t.length<6)return s.textContent='Пароль должен быть не менее 6 символов';if(t!==a)return s.textContent='Пароли не совпадают';try{console.log('Регистрируем пользователя...');const{data:n,error:c}=await supabase.auth.signUp({email:e,password:t,options:{data:{email:e}}});if(c)throw c;console.log('Auth регистрация успешна:',n.user?.id),n.user&&(await supabase.from('users').insert([{id:n.user.id,email:n.user.email,balance:1e4,role:'user',created_at:new Date().toISOString()}]),alert('Регистрация успешна! Теперь войдите в аккаунт.'),closeModal('register-modal'),showLogin())}catch(r){console.error('Ошибка регистрации:',r),s.textContent=r.message||'Ошибка регистрации'}}

async function handleLogin(){const e=document.getElementById('login-email').value.trim(),t=document.getElementById('login-password').value.trim(),a=document.getElementById('login-error');if(a.textContent='',!e||!t)return a.textContent='Заполните все поля';try{console.log('Входим...');const{data:s,error:n}=await supabase.auth.signInWithPassword({email:e,password:t});if(n)throw n;console.log('Вход успешен:',s.user?.id),s.user&&(await supabase.from('users').select('id').eq('id',s.user.id).maybeSingle(),await supabase.from('users').insert([{id:s.user.id,email:s.user.email,balance:1e4,role:'user',created_at:new Date().toISOString()}])),closeModal('login-modal'),location.reload()}catch(c){console.error('Ошибка входа:',c),a.textContent=c.message||'Неверный email или пароль'}}

async function checkAuth(){try{const{data:e,error:t}=await supabase.auth.getSession();if(t)throw t;if(e.session){state.user=e.session.user,console.log('Пользователь авторизован:',state.user.email),document.getElementById('auth-btn').style.display='none',document.getElementById('logout-btn').style.display='block',document.getElementById('user-email').textContent=state.user.email;const{data:a}=await supabase.from('users').select('role').eq('id',state.user.id).single();a?.role==='admin'&&(document.getElementById('admin-btn').style.display='block')}else console.log('Пользователь не авторизован'),document.getElementById('auth-btn').style.display='block',document.getElementById('logout-btn').style.display='none',document.getElementById('admin-btn').style.display='none',document.getElementById('user-email').textContent='Гость'}catch(s){console.error('Ошибка проверки auth:',s)}}async function logout(){await supabase.auth.signOut(),location.reload()}

async function loadData(){try{const[{data:e},{data:t}]=await Promise.all([supabase.from('cases').select('*'),supabase.from('skins').select('*')]);cases=e||[],skins=t||[],renderCases()}catch(a){console.error('Ошибка загрузки:',a)}}async function loadPlayer(){if(!state.user)return;const{data:e}=await supabase.from('users').select('balance').eq('id',state.user.id).single();e&&(state.balance=e.balance);const{data:t}=await supabase.from('player_inventory').select('skin_id').eq('player_id',state.user.id);state.inventory=t||[],updateUI(),renderInventory()}

function updateUI(){document.getElementById('balance').textContent=state.balance,document.getElementById('inventory').textContent=state.inventory.length,document.getElementById('withdraw-balance').textContent=state.balance}function renderCases(){const e=document.getElementById('cases');if(!e)return;e.innerHTML=cases.length?cases.map(e=>`<div class="case" onclick="previewCase(${e.id})"><h3>${e.emoji||'📦'} ${e.name}</h3><p>${e.price} монет</p></div>`).join(''):'<p>Кейсы отсутствуют</p>'}function renderInventory(){const e=document.getElementById('inventory-list');if(!e)return;e.innerHTML=state.inventory.length?state.inventory.map(e=>{const t=skins.find(t=>t.id===e.skin_id);return`<div class="skin">${t?.name||'Скин'} #${e.skin_id}</div>`}).join(''):'<p>Инвентарь пуст</p>'}

function previewCase(e){selectedCase=cases.find(t=>t.id===e);if(!state.user)return alert('Войдите для открытия кейсов'),showLogin();document.getElementById('preview-title').textContent=selectedCase.name,document.getElementById('preview-price').textContent=`Цена: ${selectedCase.price} монет`,document.getElementById('preview-modal').style.display='block'}async function openCase(){if(!selectedCase||!state.user)return alert('Ошибка');if(state.balance<selectedCase.price)return alert('Недостаточно средств'),closeModal('preview-modal');try{const e=await fetch('https://mute-night-5909.zummer-max405.workers.dev/api/open-case',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:state.user.id,case_id:selectedCase.id,case_price:selectedCase.price})}),t=await e.json();if(t.success){state.balance=t.newBalance,updateUI(),alert('Выиграли: '+(t.skin||'скин')),closeModal('preview-modal'),await loadPlayer()}else alert('Ошибка: '+(t.error||'неизвестно'))}catch(a){alert('Ошибка соединения')}}

function showWithdraw(){if(!state.user)return alert('Войдите для вывода'),showLogin();if(state.balance<1e3)return alert('Минимум 1000 монет');document.getElementById('withdraw-modal').style.display='block'}async function createWithdraw(){const e=parseInt(document.getElementById('withdraw-amount').value),t=document.getElementById('withdraw-tg').value.trim();if(e<1e3||e>state.balance||!t)return alert('Некорректные данные');await supabase.from('withdrawal_requests').insert([{player_id:state.user.id,amount:e,telegram_contact:t,status:'pending'}]);alert('Заявка создана!'),closeModal('withdraw-modal')}

async function adminPanel(){if(!state.user)return;document.getElementById('admin-modal').style.display='block';const{data:e}=await supabase.from('users').select('role').eq('id',state.user.id).single();if(e?.role!=='admin')return document.getElementById('admin-content').innerHTML='<p>У вас нет прав администратора</p>';showAdminTab('withdraw')}function showAdminTab(e){document.querySelectorAll('.admin-tab').forEach(t=>{t.style.display='none'}),document.querySelectorAll('.tab-btn').forEach(t=>{t.classList.remove('active')});const t=document.getElementById(`admin-${e}`);t&&(t.style.display='block'),event.target.classList.add('active'),e==='withdraw'?loadWithdrawRequests():e==='cases'?(loadCasesForAdmin(),loadAllSkinsForAdmin()):e==='skins'&&loadAllSkinsForAdmin()}async function loadWithdrawRequests(){try{const{data:e}=await supabase.from('withdrawal_requests').select('*').order('id',{ascending:!1});document.getElementById('withdraw-list').innerHTML=(e||[]).map(e=>`<div class="request-item"><strong>Заявка #${e.id}</strong><br>Игрок: ${e.player_id}<br>Сумма: ${e.amount} монет<br>Telegram: ${e.telegram_contact}<br>Статус: <span class="status-${e.status}">${e.status}</span>${e.status==='pending'?`<div style="margin-top:10px"><button onclick="approveRequest(${e.id})" style="background:#00b894;margin-right:5px">✅ Одобрить</button><button onclick="rejectRequest(${e.id})" style="background:#f72585">❌ Отклонить</button></div>`:''}</div>`).join('')}catch(t){console.error('Ошибка загрузки заявок:',t)}}async function approveRequest(e){if(!confirm('Одобрить?'))return;await supabase.from('withdrawal_requests').update({status:'approved'}).eq('id',e),adminPanel()}async function rejectRequest(e){if(!confirm('Отклонить?'))return;await supabase.from('withdrawal_requests').update({status:'rejected'}).eq('id',e),adminPanel()}async function createNewCase(){const e=document.getElementById('case-name').value.trim(),t=document.getElementById('case-price').value;if(!e||!t)return alert('Заполните поля');await supabase.from('cases').insert([{name:e,price:t,emoji:'📦'}]);alert('Кейс создан'),await loadData()}

function allowDrop(e){e.preventDefault(),e.currentTarget.classList.add('drag-over')}function dragLeave(e){e.currentTarget.classList.remove('drag-over')}function dragStart(e,t){e.dataTransfer.setData('skinId',t),e.currentTarget.classList.add('dragging')}function dragEnd(e){e.currentTarget.classList.remove('dragging')}function dropOnCase(e){e.preventDefault(),e.currentTarget.classList.remove('drag-over');if(!selectedCaseId)return alert('Сначала выберите кейс из списка слева');const t=e.dataTransfer.getData('skinId');t&&addSkinToCase(parseInt(t))}function addSkinToCase(e){if(currentCaseSkins.includes(e))return alert('Этот скин уже есть в кейсе!');currentCaseSkins.push(e),updateCaseSkinsDisplay()}function removeSkinFromCase(e){currentCaseSkins=currentCaseSkins.filter(t=>t!==e),updateCaseSkinsDisplay()}function updateCaseSkinsDisplay(){const e=document.getElementById('case-skins-list');if(!e)return;e.innerHTML=currentCaseSkins.length?currentCaseSkins.map(e=>`<div class="case-skin-item" id="skin-in-case-${e}">Скин #${e}<span class="remove-skin" onclick="removeSkinFromCase(${e})">×</span></div>`).join(''):'<p>В кейсе пока нет скинов</p>'}

async function loadCasesForAdmin(){try{const{data:e}=await supabase.from('cases').select('*').order('id'),t=document.getElementById('cases-list-admin');t&&(t.innerHTML=e.map(e=>`<div class="drag-item case-admin-item" onclick="selectCase(${e.id})" style="cursor:pointer;${selectedCaseId===e.id?'border-color:#4cc9f0':''}"><div style="font-size:24px">${e.emoji||'📦'}</div><div style="font-size:.9em">${e.name}</div><div style="font-size:.8em;opacity:.7">${e.price} монет</div><button onclick="event.stopPropagation();deleteCase(${e.id})" style="background:#f72585;padding:3px 8px;font-size:.8em;margin-top:5px">Удалить</button></div>`).join(''))}catch(a){console.error('Ошибка загрузки кейсов:',a)}}async function selectCase(e){selectedCaseId=e,document.querySelectorAll('.case-admin-item').forEach(t=>{t.style.borderColor='transparent'}),event.currentTarget.style.borderColor='#4cc9f0';const{data:t}=await supabase.from('cases').select('*').eq('id',e).single();t&&(document.getElementById('selected-case-info').innerHTML=`<h4>${t.emoji||'📦'} ${t.name}</h4><p>Цена: ${t.price} монет</p><p>ID: ${t.id}</p>`),await loadCaseSkins(e),document.getElementById('save-case-btn').style.display='block'}async function loadCaseSkins(e){try{const{data:t}=await supabase.from('case_skins').select(`skin_id,skins(*)`).eq('case_id',e);currentCaseSkins=t.map(e=>e.skin_id);const a=document.getElementById('case-skins-list');a&&(a.innerHTML=t.length?t.map(e=>`<div class="case-skin-item" id="skin-in-case-${e.skin_id}">${e.skins?.emoji||'🎮'} ${e.skins?.name||'Скин'} <span class="remove-skin" onclick="removeSkinFromCase(${e.skin_id})">×</span></div>`).join(''):'<p>В кейсе пока нет скинов</p>')}catch(s){console.error('Ошибка загрузки скинов кейса:',s)}}

async function saveCaseSkins(){if(!selectedCaseId)return alert('Сначала выберите кейс');try{await supabase.from('case_skins').delete().eq('case_id',selectedCaseId);if(currentCaseSkins.length){const e=currentCaseSkins.map(e=>({case_id:selectedCaseId,skin_id:e,weight:100}));await supabase.from('case_skins').insert(e)}alert(`Сохранено! В кейс добавлено ${currentCaseSkins.length} скинов`),await loadCaseSkins(selectedCaseId)}catch(e){console.error('Ошибка сохранения кейса:',e),alert('Ошибка сохранения: '+e.message)}}

async function loadAllSkinsForAdmin(){try{const{data:e}=await supabase.from('skins').select('*').order('id'),t=document.getElementById('skins-list-admin');t&&(t.innerHTML=e.map(e=>`<div class="drag-item" draggable="true" ondragstart="dragStart(event,${e.id})" ondragend="dragEnd(event)" id="skin-${e.id}"><div style="font-size:24px">${e.emoji||'🎮'}</div><div style="font-size:.9em">${e.name}</div><div style="font-size:.8em;opacity:.7">${e.price} монет</div><div style="font-size:.7em;color:${getRarityColor(e.rarity)}">${getRarityName(e.rarity)}</div><button onclick="event.stopPropagation();deleteSkin(${e.id})" style="background:#f72585;padding:3px 8px;font-size:.8em;margin-top:5px">Удалить</button></div>`).join(''))}catch(a){console.error('Ошибка загрузки скинов:',a)}}function getRarityColor(e){switch(e){case'common':return'#4cc9f0';case'rare':return'#4361ee';case'epic':return'#7209b7';case'legendary':return'#f72585';default:return'#ffffff'}}function getRarityName(e){switch(e){case'common':return'Обычный';case'rare':return'Редкий';case'epic':return'Эпический';case'legendary':return'Легендарный';default:return'Обычный'}}

async function createNewSkin(){const e=document.getElementById('skin-name').value.trim(),t=parseInt(document.getElementById('skin-price').value),a=document.getElementById('skin-rarity').value,s=document.getElementById('skin-emoji').value.trim()||'🎮',n=document.getElementById('skin-image').value.trim();if(!e||!t||t<=0)return alert('Введите название и цену скина');try{await supabase.from('skins').insert([{name:e,price:t,rarity:a,emoji:s,image_url:n||null}]);alert('Скин успешно создан!'),document.getElementById('skin-name').value='',document.getElementById('skin-price').value='100',document.getElementById('skin-emoji').value='🎮',document.getElementById('skin-image').value='',await loadAllSkinsForAdmin()}catch(c){console.error('Ошибка создания скина:',c),alert('Ошибка: '+c.message)}}

async function deleteCase(e){if(!confirm('Удалить этот кейс? Все связи со скинами также удалятся.'))return;try{await supabase.from('cases').delete().eq('id',e);alert('Кейс удален'),await loadCasesForAdmin();if(selectedCaseId===e){selectedCaseId=null,document.getElementById('selected-case-info').innerHTML='<p>Выберите кейс слева</p>',document.getElementById('case-skins-list').innerHTML='',document.getElementById('save-case-btn').style.display='none'}}catch(t){console.error('Ошибка удаления кейса:',t),alert('Ошибка удаления: '+t.message)}}async function deleteSkin(e){if(!confirm('Удалить этот скин? Он также удалится из всех кейсов.'))return;try{await supabase.from('skins').delete().eq('id',e);alert('Скин удален'),await loadAllSkinsForAdmin();currentCaseSkins.includes(e)&&(currentCaseSkins=currentCaseSkins.filter(t=>t!==e),updateCaseSkinsDisplay())}catch(t){console.error('Ошибка удаления скина:',t),alert('Ошибка удаления: '+t.message)}}

async function openCaseWithSkins(){if(!selectedCase||!state.user)return alert('Ошибка');if(state.balance<selectedCase.price)return alert('Недостаточно средств'),closeModal('preview-modal');try{const{data:e}=await supabase.from('case_skins').select(`skin_id,weight,skins(*)`).eq('case_id',selectedCase.id);if(!e||!e.length)return alert('В этом кейсе нет скинов!');let t=e.reduce((t,a)=>t+(a.weight||100),0),a=Math.random()*t,s=null;for(const t of e){a-=t.weight||100;if(a<=0){s=t.skins;break}}s||(s=e[0].skins);const n=state.balance-selectedCase.price;await supabase.from('users').update({balance:n}).eq('id',state.user.id),await supabase.from('player_inventory').insert([{player_id:state.user.id,skin_id:s.id,created_at:new Date().toISOString()}]),state.balance=n,updateUI(),alert(`🎉 Вы выиграли: ${s.emoji||'🎮'} ${s.name} (${getRarityName(s.rarity)})!`),closeModal('preview-modal'),await loadPlayer()}catch(c){console.error('Ошибка открытия кейса:',c),alert('Ошибка: '+(c.message||'Не удалось открыть кейс'))}}

document.addEventListener('DOMContentLoaded',init);