// Конфиг
const SB_URL='https://jttsgizkuyipolcnvanc.supabase.co',SB_KEY='sb_publishable_MV93VmhU8U2I-2m8UquKkw_Eril4zvp',supabase=window.supabase.createClient(SB_URL,SB_KEY);
let state={user:null,balance:0,inventory:[]},cases=[],skins=[],selectedCase=null,selectedCaseId=null,currentCaseSkins=[];

async function init(){console.log('Инициализация...');await checkAuth();await loadData();if(state.user)await loadPlayer();setupModalListeners();updateUI();}
function setupModalListeners(){document.querySelectorAll('.modal').forEach(e=>{e.addEventListener('click',function(t){t.target===this&&(this.style.display='none')})});}

// Аутентификация
async function checkAuth(){try{const{data:e}=await supabase.auth.getSession();if(e.session){state.user=e.session.user,document.getElementById('auth-btn').style.display='none',document.getElementById('logout-btn').style.display='block',document.getElementById('user-email').textContent=state.user.email;const{data:t}=await supabase.from('users').select('role').eq('id',state.user.id).single();t?.role==='admin'&&(document.getElementById('admin-btn').style.display='block')}else document.getElementById('auth-btn').style.display='block',document.getElementById('logout-btn').style.display='none',document.getElementById('admin-btn').style.display='none',document.getElementById('user-email').textContent='Гость'}catch(t){console.error('Ошибка auth:',t)}}async function logout(){await supabase.auth.signOut(),location.reload()}

// Данные
async function loadData(){try{const[{data:e},{data:t}]=await Promise.all([supabase.from('cases').select('*'),supabase.from('skins').select('*')]);cases=e||[],skins=t||[],renderCases()}catch(a){console.error('Ошибка загрузки:',a)}}async function loadPlayer(){if(!state.user)return;const{data:e}=await supabase.from('users').select('balance').eq('id',state.user.id).single();e&&(state.balance=e.balance);const{data:t}=await supabase.from('player_inventory').select('skin_id').eq('player_id',state.user.id);state.inventory=t||[],updateUI(),renderInventory()}

// UI
function updateUI(){document.getElementById('balance').textContent=state.balance,document.getElementById('inventory').textContent=state.inventory.length}function renderCases(){const e=document.getElementById('cases');e&&(e.innerHTML=cases.length?cases.map(e=>`<div class="case" onclick="previewCase(${e.id})"><h3>${e.emoji||'📦'} ${e.name}</h3><p>${e.price} монет</p></div>`).join(''):'<p>Кейсы отсутствуют</p>')}function renderInventory(){const e=document.getElementById('inventory-list');e&&(e.innerHTML=state.inventory.length?state.inventory.map(e=>{const t=skins.find(t=>t.id===e.skin_id);return`<div class="skin">${t?.name||'Скин'} #${e.skin_id}</div>`}).join(''):'<p>Инвентарь пуст</p>')}

// Кейсы
function previewCase(e){selectedCase=cases.find(t=>t.id===e);if(!state.user)return alert('Войдите для открытия кейсов'),showLogin();document.getElementById('preview-title').textContent=selectedCase.name,document.getElementById('preview-price').textContent=`Цена: ${selectedCase.price} монет`,document.getElementById('preview-modal').style.display='block'}async function openCase(){if(!selectedCase||!state.user)return alert('Ошибка');if(state.balance<selectedCase.price)return alert('Недостаточно средств'),closeModal('preview-modal');try{const e=await fetch('https://mute-night-5909.zummer-max405.workers.dev/api/open-case',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:state.user.id,case_id:selectedCase.id,case_price:selectedCase.price})}),t=await e.json();t.success?(state.balance=t.newBalance,updateUI(),alert('Выиграли: '+(t.skin||'скин')),closeModal('preview-modal'),await loadPlayer()):alert('Ошибка: '+(t.error||'неизвестно'))}catch(a){alert('Ошибка соединения')}}

// Админка
async function adminPanel(){if(!state.user)return;document.getElementById('admin-modal').style.display='block';const{data:e}=await supabase.from('users').select('role').eq('id',state.user.id).single();if(e?.role!=='admin')return document.getElementById('admin-content').innerHTML='<p>Нет прав администратора</p>';await loadAdminData()}async function loadAdminData(){await Promise.all([loadAdminCases(),loadAdminSkins()])}

// Загрузка данных для админки
async function loadAdminCases(){try{const{data:e}=await supabase.from('cases').select('*').order('id'),t=document.getElementById('admin-cases-list');t&&(t.innerHTML=e.map(e=>`<div class="admin-case-item ${selectedCaseId===e.id?'selected':''}" onclick="selectAdminCase(${e.id})"><div style="font-size:24px">${e.emoji||'📦'}</div><div>${e.name}</div><div style="font-size:.8em">${e.price} монет</div></div>`).join(''))}catch(t){console.error('Ошибка загрузки кейсов:',t)}}async function selectAdminCase(e){selectedCaseId=e;const{data:t}=await supabase.from('cases').select('*').eq('id',e).single();if(t){document.getElementById('selected-case-info').innerHTML=`<h4>${t.emoji||'📦'} ${t.name}</h4><p>Цена: ${t.price} монет</p>`;await loadCaseSkins(e)}}

async function loadAdminSkins(){try{const{data:e}=await supabase.from('skins').select('*').order('id'),t=document.getElementById('admin-skins-list');t&&(t.innerHTML=e.map(e=>`<div class="admin-skin-item" draggable="true" ondragstart="dragStart(event,${e.id})" ondragend="dragEnd(event)" data-id="${e.id}" title="${e.name} - ${e.price} монет (${getRarityName(e.rarity)})">${e.emoji||'🎮'}<div style="font-size:.7em">${e.name}</div></div>`).join(''))}catch(t){console.error('Ошибка загрузки скинов:',t)}}

// Drag & Drop
function allowDrop(e){e.preventDefault(),e.currentTarget.classList.add('drag-over')}function dragLeave(e){e.currentTarget.classList.remove('drag-over')}function dragStart(e,t){e.dataTransfer.setData('skinId',t),e.currentTarget.classList.add('dragging')}function dragEnd(e){e.currentTarget.classList.remove('dragging')}
function dropOnCase(e){e.preventDefault(),e.currentTarget.classList.remove('drag-over');const t=e.dataTransfer.getData('skinId');if(!t||!selectedCaseId)return;const a=parseInt(t),s=parseInt(prompt('Укажите шанс выпадения (1-100):','10'))||10;if(s<1||s>100)return alert('Шанс должен быть от 1 до 100');addSkinToCase(a,s)}

// Работа с кейсами
async function loadCaseSkins(e){try{const{data:t}=await supabase.from('case_skins').select(`skin_id,weight,skins(name,emoji)`).eq('case_id',e),a=document.getElementById('case-skins-list');currentCaseSkins=t||[],a&&(a.innerHTML=t.length?t.map(t=>`<div class="case-skin-item"><span>${t.skins?.emoji||'🎮'} ${t.skins?.name||'Скин'}</span><input type="number" value="${t.weight||10}" min="1" max="100" onchange="updateSkinWeight(${t.skin_id},this.value)" style="width:60px;margin:0 5px;"><button onclick="removeSkinFromCase(${t.skin_id})">×</button></div>`).join(''):'<p>Перетащите сюда скины</p>')}catch(s){console.error('Ошибка загрузки скинов:',s)}}
function addSkinToCase(e,t){if(currentCaseSkins.find(a=>a.skin_id===e))return alert('Этот скин уже в кейсе');currentCaseSkins.push({skin_id:e,weight:t}),updateCaseSkinsDisplay()}function updateSkinWeight(e,t){const a=currentCaseSkins.findIndex(a=>a.skin_id===e);a>-1&&(currentCaseSkins[a].weight=parseInt(t)||10)}function removeSkinFromCase(e){currentCaseSkins=currentCaseSkins.filter(t=>t.skin_id!==e),updateCaseSkinsDisplay()}function updateCaseSkinsDisplay(){const e=document.getElementById('case-skins-list');e&&(e.innerHTML=currentCaseSkins.length?currentCaseSkins.map(e=>`<div class="case-skin-item"><span>Скин #${e.skin_id}</span><input type="number" value="${e.weight||10}" min="1" max="100" onchange="updateSkinWeight(${e.skin_id},this.value)" style="width:60px;margin:0 5px;"><button onclick="removeSkinFromCase(${e.skin_id})">×</button></div>`).join(''):'<p>Перетащите сюда скины</p>')}

// Сохранение кейса
async function saveCaseSkins(){if(!selectedCaseId||!currentCaseSkins.length)return alert('Выберите кейс и добавьте скины');try{await supabase.from('case_skins').delete().eq('case_id',selectedCaseId);const e=currentCaseSkins.map(e=>({case_id:selectedCaseId,skin_id:e.skin_id,weight:e.weight||10}));await supabase.from('case_skins').insert(e),alert(`Сохранено! ${e.length} скинов в кейсе`),await loadCaseSkins(selectedCaseId)}catch(e){console.error('Ошибка сохранения:',e),alert('Ошибка: '+e.message)}}

// Создание кейса/скина
async function createNewCase(){const e=document.getElementById('new-case-name').value.trim(),t=parseInt(document.getElementById('new-case-price').value);if(!e||!t||t<=0)return alert('Введите название и цену');try{await supabase.from('cases').insert([{name:e,price:t,emoji:'📦'}]),alert('Кейс создан'),document.getElementById('new-case-name').value='',document.getElementById('new-case-price').value='',await loadAdminCases(),await loadData()}catch(a){alert('Ошибка: '+a.message)}}async function createNewSkin(){const e=document.getElementById('new-skin-name').value.trim(),t=parseInt(document.getElementById('new-skin-price').value);if(!e||!t||t<=0)return alert('Введите название и цену');try{await supabase.from('skins').insert([{name:e,price:t,rarity:'common',emoji:'🎮'}]),alert('Скин создан'),document.getElementById('new-skin-name').value='',document.getElementById('new-skin-price').value='100',await loadAdminSkins()}catch(a){alert('Ошибка: '+a.message)}}

// Утилиты
function getRarityName(e){return{common:'Обычный',rare:'Редкий',epic:'Эпический',legendary:'Легендарный'}[e]||'Обычный'}function showAuth(){document.getElementById('login-modal').style.display='block'}function showLogin(){document.getElementById('login-modal').style.display='block'}function showRegister(){document.getElementById('register-modal').style.display='block',document.getElementById('login-modal').style.display='none'}function closeModal(e){document.getElementById(e).style.display='none'}

// Регистрация/вход
async function handleRegister(){const e=document.getElementById('register-email').value.trim(),t=document.getElementById('register-password').value.trim();if(!e||!t||t.length<6)return alert('Заполните email и пароль (мин. 6 символов)');try{const{error:a}=await supabase.auth.signUp({email:e,password:t});a?alert('Ошибка: '+a.message):(alert('Регистрация успешна!'),closeModal('register-modal'),showLogin())}catch(s){alert('Ошибка регистрации')}}async function handleLogin(){const e=document.getElementById('login-email').value.trim(),t=document.getElementById('login-password').value.trim();if(!e||!t)return alert('Заполните поля');try{const{error:a}=await supabase.auth.signInWithPassword({email:e,password:t});a?alert('Ошибка: '+a.message):(closeModal('login-modal'),location.reload())}catch(s){alert('Ошибка входа')}}

// Запуск
document.addEventListener('DOMContentLoaded',init);